// <auto-generated />
using System;
using DDDSample1.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DDDNetCore.Migrations
{
    [DbContext(typeof(DDDSample1DbContext))]
    [Migration("20260801201409_NormalizeProductOptions")]
    partial class NormalizeProductOptions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("dddnetcore.Domain.Carrinhos.Carrinho", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Carrinhos");
                });

            modelBuilder.Entity("dddnetcore.Domain.Categorias.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NomeCategoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("dddnetcore.Domain.Clientes.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MoradaCliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeCliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("dddnetcore.Domain.Colecoes.Colecao", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataAtualizacaoColecao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacaoColecao")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescricaoColecao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstadoColecao")
                        .HasColumnType("int");

                    b.Property<string>("NomeColecao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Colecoes");
                });

            modelBuilder.Entity("dddnetcore.Domain.FotoColecoes.FotoColecao", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ColecaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UrlColecao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ColecaoId");

                    b.ToTable("FotoColecoes");
                });

            modelBuilder.Entity("dddnetcore.Domain.FotoProdutos.FotoProduto", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UrlProduto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoId");

                    b.ToTable("FotoProdutos");
                });

            modelBuilder.Entity("dddnetcore.Domain.GruposVariantes.GrupoVariantes", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.ToTable("GruposVariantes");
                });

            modelBuilder.Entity("dddnetcore.Domain.GruposVariantes.OpcaoProduto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GrupoVariantesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GrupoVariantesId", "Nome")
                        .IsUnique();

                    b.ToTable("OpcoesProduto", (string)null);
                });

            modelBuilder.Entity("dddnetcore.Domain.GruposVariantes.ValorOpcaoProduto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CorHex")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("OpcaoProdutoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("OpcaoProdutoId", "Valor")
                        .IsUnique();

                    b.ToTable("ValoresOpcaoProduto", (string)null);
                });

            modelBuilder.Entity("dddnetcore.Domain.GruposVariantes.VarianteProduto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativa")
                        .HasColumnType("bit");

                    b.Property<Guid>("GrupoVariantesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.Property<double?>("Preco")
                        .HasColumnType("float");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GrupoVariantesId");

                    b.ToTable("VariantesProduto", (string)null);
                });

            modelBuilder.Entity("dddnetcore.Domain.GruposVariantes.VarianteProdutoValor", b =>
                {
                    b.Property<Guid>("VarianteProdutoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ValorOpcaoProdutoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("VarianteProdutoId", "ValorOpcaoProdutoId");

                    b.HasIndex("ValorOpcaoProdutoId");

                    b.ToTable("VariantesProdutoValores", (string)null);
                });

            modelBuilder.Entity("dddnetcore.Domain.ItensCarrinho.ItemCarrinho", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CarrinhoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarrinhoId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("ItensCarrinho");
                });

            modelBuilder.Entity("dddnetcore.Domain.Produtos.Produto", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ColecaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DescricaoProduto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("GrupoVariantesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NomeProduto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PrecoProduto")
                        .HasColumnType("float");

                    b.Property<int>("StockProduto")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("ColecaoId");

                    b.HasIndex("GrupoVariantesId");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("dddnetcore.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasDefaultValue("cliente");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("dddnetcore.Domain.VendaProdutos.VendaProduto", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DetalhesVariante")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<Guid>("VendaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoId");

                    b.HasIndex("VendaId");

                    b.ToTable("VendaProdutos");
                });

            modelBuilder.Entity("dddnetcore.Domain.Vendas.Venda", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodigoRastreio")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime?>("DataEnvio")
                        .HasColumnType("datetime2");

                    b.Property<string>("MetodoPagamento")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("NotasInternas")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("PagamentoEstado")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("PagamentoProvider")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("PagamentoReferencia")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Transportadora")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("UrlRastreio")
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<DateTime>("VendaData")
                        .HasColumnType("datetime2");

                    b.Property<string>("VendaEstado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("VendaTotal")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Vendas");
                });

            modelBuilder.Entity("dddnetcore.Domain.Carrinhos.Carrinho", b =>
                {
                    b.HasOne("dddnetcore.Domain.Clientes.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("dddnetcore.Domain.Clientes.Cliente", b =>
                {
                    b.OwnsOne("dddnetcore.Domain.Clientes.EmailCliente", "EmailCliente", b1 =>
                        {
                            b1.Property<Guid>("ClienteId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("nvarchar(150)")
                                .HasColumnName("EmailCliente");

                            b1.HasKey("ClienteId");

                            b1.ToTable("Clientes");

                            b1.WithOwner()
                                .HasForeignKey("ClienteId");
                        });

                    b.Navigation("EmailCliente")
                        .IsRequired();
                });

            modelBuilder.Entity("dddnetcore.Domain.FotoColecoes.FotoColecao", b =>
                {
                    b.HasOne("dddnetcore.Domain.Colecoes.Colecao", null)
                        .WithMany("FotoColecao")
                        .HasForeignKey("ColecaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("dddnetcore.Domain.FotoProdutos.FotoProduto", b =>
                {
                    b.HasOne("dddnetcore.Domain.Produtos.Produto", null)
                        .WithMany("FotoProduto")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("dddnetcore.Domain.GruposVariantes.OpcaoProduto", b =>
                {
                    b.HasOne("dddnetcore.Domain.GruposVariantes.GrupoVariantes", "GrupoVariantes")
                        .WithMany("Opcoes")
                        .HasForeignKey("GrupoVariantesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GrupoVariantes");
                });

            modelBuilder.Entity("dddnetcore.Domain.GruposVariantes.ValorOpcaoProduto", b =>
                {
                    b.HasOne("dddnetcore.Domain.GruposVariantes.OpcaoProduto", "Opcao")
                        .WithMany("Valores")
                        .HasForeignKey("OpcaoProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Opcao");
                });

            modelBuilder.Entity("dddnetcore.Domain.GruposVariantes.VarianteProduto", b =>
                {
                    b.HasOne("dddnetcore.Domain.GruposVariantes.GrupoVariantes", "GrupoVariantes")
                        .WithMany("Variantes")
                        .HasForeignKey("GrupoVariantesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GrupoVariantes");
                });

            modelBuilder.Entity("dddnetcore.Domain.GruposVariantes.VarianteProdutoValor", b =>
                {
                    b.HasOne("dddnetcore.Domain.GruposVariantes.ValorOpcaoProduto", "ValorOpcao")
                        .WithMany()
                        .HasForeignKey("ValorOpcaoProdutoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("dddnetcore.Domain.GruposVariantes.VarianteProduto", "Variante")
                        .WithMany("Valores")
                        .HasForeignKey("VarianteProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ValorOpcao");

                    b.Navigation("Variante");
                });

            modelBuilder.Entity("dddnetcore.Domain.ItensCarrinho.ItemCarrinho", b =>
                {
                    b.HasOne("dddnetcore.Domain.Carrinhos.Carrinho", null)
                        .WithMany("Itens")
                        .HasForeignKey("CarrinhoId");

                    b.HasOne("dddnetcore.Domain.Produtos.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("dddnetcore.Domain.Produtos.Produto", b =>
                {
                    b.HasOne("dddnetcore.Domain.Categorias.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dddnetcore.Domain.Colecoes.Colecao", null)
                        .WithMany("Produto")
                        .HasForeignKey("ColecaoId");

                    b.HasOne("dddnetcore.Domain.GruposVariantes.GrupoVariantes", "GrupoVariantes")
                        .WithMany()
                        .HasForeignKey("GrupoVariantesId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Categoria");

                    b.Navigation("GrupoVariantes");
                });

            modelBuilder.Entity("dddnetcore.Domain.Users.User", b =>
                {
                    b.HasOne("dddnetcore.Domain.Clientes.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("dddnetcore.Domain.Users.UserName", "UserName", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Nome")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("UserName");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("dddnetcore.Domain.Users.UserPassword", "UserPassword", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Password")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("PasswordHash");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Cliente");

                    b.Navigation("UserName")
                        .IsRequired();

                    b.Navigation("UserPassword")
                        .IsRequired();
                });

            modelBuilder.Entity("dddnetcore.Domain.VendaProdutos.VendaProduto", b =>
                {
                    b.HasOne("dddnetcore.Domain.Produtos.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dddnetcore.Domain.Vendas.Venda", "Venda")
                        .WithMany()
                        .HasForeignKey("VendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");

                    b.Navigation("Venda");
                });

            modelBuilder.Entity("dddnetcore.Domain.Vendas.Venda", b =>
                {
                    b.HasOne("dddnetcore.Domain.Clientes.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("dddnetcore.Domain.Carrinhos.Carrinho", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("dddnetcore.Domain.Colecoes.Colecao", b =>
                {
                    b.Navigation("FotoColecao");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("dddnetcore.Domain.GruposVariantes.GrupoVariantes", b =>
                {
                    b.Navigation("Opcoes");

                    b.Navigation("Variantes");
                });

            modelBuilder.Entity("dddnetcore.Domain.GruposVariantes.OpcaoProduto", b =>
                {
                    b.Navigation("Valores");
                });

            modelBuilder.Entity("dddnetcore.Domain.GruposVariantes.VarianteProduto", b =>
                {
                    b.Navigation("Valores");
                });

            modelBuilder.Entity("dddnetcore.Domain.Produtos.Produto", b =>
                {
                    b.Navigation("FotoProduto");
                });
#pragma warning restore 612, 618
        }
    }
}
